# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpRedfish < Formula
  desc "Local MCP server for interacting with server BMCs via the Redfish API"
  homepage "https://github.com/conallob/mcp-redfish"
  version "0.0.2"
  license "BSD-3-Clause"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/conallob/mcp-redfish/releases/download/v0.0.2/mcp-redfish_darwin_amd64.tar.gz"
      sha256 "9dd38291e669f633b466a3bf274acddc0caf654f3e69709fa8696c0a4c896ccb"

      define_method(:install) do
        bin.install "mcp-redfish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/conallob/mcp-redfish/releases/download/v0.0.2/mcp-redfish_darwin_arm64.tar.gz"
      sha256 "22fcc1301245a6a3604c32040c85935624a6bd6af2048f1e151940975c0630ac"

      define_method(:install) do
        bin.install "mcp-redfish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/conallob/mcp-redfish/releases/download/v0.0.2/mcp-redfish_linux_amd64.tar.gz"
      sha256 "b65a0526ed7e3906a866b6038dbbd7539b62fa7adb313c3dc6a01a17c08071b2"
      define_method(:install) do
        bin.install "mcp-redfish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/conallob/mcp-redfish/releases/download/v0.0.2/mcp-redfish_linux_arm64.tar.gz"
      sha256 "409ef51c2bf9d38434143a9c7f2be8c89ab08970115f6a180a9862dd109e33b1"
      define_method(:install) do
        bin.install "mcp-redfish"
      end
    end
  end

  test do
    system "#{bin}/mcp-redfish", "--version"
  end
end
