# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CodingInterviewPatternDrill < Formula
  desc "Pattern recognition trainer for coding interviews — CLI and browser UI"
  homepage "https://github.com/conallob/coding-interview-pattern-drill"
  version "0.0.8"
  license "MIT"

  on_macos do
    url "https://github.com/conallob/coding-interview-pattern-drill/releases/download/v0.0.8/coding-interview-pattern-drill_Darwin_all.tar.gz"
    sha256 "fdd0996f23280a1de25a64aa4e3643413fb1d3ac581d23c7d2a8fc05bc591064"

    define_method(:install) do
      bin.install "coding-interview-pattern-drill"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/conallob/coding-interview-pattern-drill/releases/download/v0.0.8/coding-interview-pattern-drill_Linux_x86_64.tar.gz"
      sha256 "6a2c10992d51ba82f1ce0739d9a2f99a83324ad44131e873d65c627deea0e863"
      define_method(:install) do
        bin.install "coding-interview-pattern-drill"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/conallob/coding-interview-pattern-drill/releases/download/v0.0.8/coding-interview-pattern-drill_Linux_arm64.tar.gz"
      sha256 "8aeb8711377a73eb8b3a429a2b1e21ffc363cc800da45edb164b4880ef8c787f"
      define_method(:install) do
        bin.install "coding-interview-pattern-drill"
      end
    end
  end

  test do
    system "#{bin}/coding-interview-pattern-drill", "--list-tags"
  end
end
