# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CodingInterviewPatternDrill < Formula
  desc "Pattern recognition trainer for coding interviews — CLI and browser UI"
  homepage "https://github.com/conallob/coding-interview-pop-quiz"
  version "0.0.1"
  license "MIT"

  on_macos do
    url "https://github.com/conallob/coding-interview-pop-quiz/releases/download/v0.0.1/coding-interview-pattern-drill_Darwin_all.tar.gz"
    sha256 "a09c139b569b6cabc2dd4bb060b9d3a6adf08c496699737d7b271652f02af83d"

    define_method(:install) do
      bin.install "coding-interview-pattern-drill"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/conallob/coding-interview-pop-quiz/releases/download/v0.0.1/coding-interview-pattern-drill_Linux_x86_64.tar.gz"
      sha256 "756ad37fec7f73dcd7a382d27d0d50273baf20492b1d4b9a75e7a9e5fd6cacbd"
      define_method(:install) do
        bin.install "coding-interview-pattern-drill"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/conallob/coding-interview-pop-quiz/releases/download/v0.0.1/coding-interview-pattern-drill_Linux_arm64.tar.gz"
      sha256 "eef8029a780685c50b560955bd263efb6f177706f87203f373cce7db275564d9"
      define_method(:install) do
        bin.install "coding-interview-pattern-drill"
      end
    end
  end

  test do
    system "#{bin}/coding-interview-pattern-drill", "--list-tags"
  end
end
