# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CodingInterviewPatternDrill < Formula
  desc "Pattern recognition trainer for coding interviews — CLI and browser UI"
  homepage "https://github.com/conallob/coding-interview-pattern-drill"
  version "0.0.7"
  license "MIT"

  on_macos do
    url "https://github.com/conallob/coding-interview-pattern-drill/releases/download/v0.0.7/coding-interview-pattern-drill_Darwin_all.tar.gz"
    sha256 "76c39739cfab7afab05b93fb82218293c4202463a27dca78f5553d847b39fb06"

    define_method(:install) do
      bin.install "coding-interview-pattern-drill"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/conallob/coding-interview-pattern-drill/releases/download/v0.0.7/coding-interview-pattern-drill_Linux_x86_64.tar.gz"
      sha256 "fe0e55ab256774d999a19e0404ad25f77338431e08cd29ad01b95e210859d6b6"
      define_method(:install) do
        bin.install "coding-interview-pattern-drill"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/conallob/coding-interview-pattern-drill/releases/download/v0.0.7/coding-interview-pattern-drill_Linux_arm64.tar.gz"
      sha256 "9d94f75d600157f1c7c1f498894a2b971ce1a24badc8c8dbb528a96fee77a08a"
      define_method(:install) do
        bin.install "coding-interview-pattern-drill"
      end
    end
  end

  test do
    system "#{bin}/coding-interview-pattern-drill", "--list-tags"
  end
end
