# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JiraBeadsSync < Formula
  desc "Sync Jira task trees with beads issues (bidirectional)"
  homepage "https://github.com/conallob/jira-beads-sync"
  version "0.0.1"
  license "BSD-3-Clause"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/conallob/jira-beads-sync/releases/download/v0.0.1/jira-beads-sync_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "cf090ad1384a436a9ce79d1bc8d0d311c369df0a61c5a04ed7a1b6ccfa0bb53b"

      def install
        bin.install "jira-beads-sync"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/conallob/jira-beads-sync/releases/download/v0.0.1/jira-beads-sync_0.0.1_Darwin_arm64.tar.gz"
      sha256 "d3190602f5d1139b240228de234cbc7ca4f40d6ff730b63657ba0a52625a0012"

      def install
        bin.install "jira-beads-sync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/conallob/jira-beads-sync/releases/download/v0.0.1/jira-beads-sync_0.0.1_Linux_x86_64.tar.gz"
      sha256 "d7f1d50ec09b2c9d9827ccc3e8cf8001676ec8b6679e0e0c91db2b3795237f89"
      def install
        bin.install "jira-beads-sync"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/conallob/jira-beads-sync/releases/download/v0.0.1/jira-beads-sync_0.0.1_Linux_arm64.tar.gz"
      sha256 "f2ced1eff7b7d148ec01eecd13c58d485a30006b6fff749b70e1dceda53e089a"
      def install
        bin.install "jira-beads-sync"
      end
    end
  end

  test do
    system "#{bin}/jira-beads-sync version"
  end
end
