# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JiraBeadsSync < Formula
  desc "Sync Jira task trees with beads issues (bidirectional)"
  homepage "https://github.com/conallob/jira-beads-sync"
  version "0.0.3"
  license "BSD-3-Clause"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/conallob/jira-beads-sync/releases/download/v0.0.3/jira-beads-sync_0.0.3_Darwin_x86_64.tar.gz"
      sha256 "61b392c561916d72d88c22a0fcd9fc760b07a9fb3aeed51ebc495410ed9d0ab9"

      def install
        bin.install "jira-beads-sync"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/conallob/jira-beads-sync/releases/download/v0.0.3/jira-beads-sync_0.0.3_Darwin_arm64.tar.gz"
      sha256 "2b7f658d765fb790a92dc0b139409c14603e37d10b5ec85d07fa55c944c72aaa"

      def install
        bin.install "jira-beads-sync"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/conallob/jira-beads-sync/releases/download/v0.0.3/jira-beads-sync_0.0.3_Linux_x86_64.tar.gz"
      sha256 "ee871f7bb13fdbea4ec7bc2079bfc09c594678165df93cc1ae78f6c33e11d88c"
      def install
        bin.install "jira-beads-sync"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/conallob/jira-beads-sync/releases/download/v0.0.3/jira-beads-sync_0.0.3_Linux_arm64.tar.gz"
      sha256 "5dd3742f2a2131b668bfa2cb8d6f0ba071f3e84d39dcd52ec21ad0ff789d0585"
      def install
        bin.install "jira-beads-sync"
      end
    end
  end

  test do
    system "#{bin}/jira-beads-sync version"
  end
end
