# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpGoogleSheets < Formula
  desc "MCP server for Google Sheets API integration"
  homepage "https://github.com/conallob/mcp-google-sheets"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/conallob/mcp-google-sheets/releases/download/v0.0.2/mcp-google-sheets_0.0.2_Darwin_x86_64.tar.gz"
      sha256 "9b2b64d8253c75f4637db1678580d087233c579ccf903e5efafc59b1d571543e"

      def install
        bin.install "mcp-google-sheets"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/conallob/mcp-google-sheets/releases/download/v0.0.2/mcp-google-sheets_0.0.2_Darwin_arm64.tar.gz"
      sha256 "5799107b3076e366cbe0cf0542093b0fe427e8b2051104edf5bbac01d5fb0587"

      def install
        bin.install "mcp-google-sheets"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/conallob/mcp-google-sheets/releases/download/v0.0.2/mcp-google-sheets_0.0.2_Linux_x86_64.tar.gz"
      sha256 "6c50dcd70d2b08c45ecc599d38a9db8224a6ea4921efe6323f2b1b6cb4516476"
      def install
        bin.install "mcp-google-sheets"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/conallob/mcp-google-sheets/releases/download/v0.0.2/mcp-google-sheets_0.0.2_Linux_arm64.tar.gz"
      sha256 "67b3d2cac4d258cfbd3e562c59fbf50209deab0b244af05d019bb8650948981e"
      def install
        bin.install "mcp-google-sheets"
      end
    end
  end

  def caveats
    <<~EOS
      To use mcp-google-sheets, you need to:
      1. Set up Google Sheets API credentials (see SETUP.md)
      2. Set the GOOGLE_APPLICATION_CREDENTIALS environment variable

      For detailed setup instructions, visit:
      https://github.com/conallob/mcp-google-sheets/blob/main/SETUP.md
    EOS
  end

  test do
    system "#{bin}/mcp-google-sheets", "--version"
  end
end
