# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpOmnifocus < Formula
  desc "MCP server for interacting with OmniFocus Pro through its automation API"
  homepage "https://github.com/conall/mcp-omnifocus"
  version "0.0.3"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/conallob/mcp-omnifocus/releases/download/v0.0.3/mcp-omnifocus_0.0.3_darwin_x86_64.tar.gz"
    sha256 "5516dad6e22978902066f6f1480cc3ce04628f737a20f7d9b3cf3c0cc1b1a783"

    def install
      bin.install "mcp-omnifocus"
      (share/"mcp-omnifocus").install Dir["scripts/*.jxa"]
      (share/"mcp-omnifocus").install "config-example.json"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/conallob/mcp-omnifocus/releases/download/v0.0.3/mcp-omnifocus_0.0.3_darwin_arm64.tar.gz"
    sha256 "7d69632aa216b5149137401b4fd7ddea6fcec9da75af171cd2dc3823f2a6af3c"

    def install
      bin.install "mcp-omnifocus"
      (share/"mcp-omnifocus").install Dir["scripts/*.jxa"]
      (share/"mcp-omnifocus").install "config-example.json"
    end
  end

  def caveats
    <<~EOS
      The JXA scripts are installed to:
        #{share}/mcp-omnifocus/scripts/

      An example configuration file is available at:
        #{share}/mcp-omnifocus/config-example.json

      Follow the Quick Start Guide for setup instructions:
        https://github.com/conall/mcp-omnifocus/blob/main/QUICKSTART.md
    EOS
  end
end
