# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpOmnifocus < Formula
  desc "MCP server for interacting with OmniFocus Pro through its automation API"
  homepage "https://github.com/conall/mcp-omnifocus"
  version "0.0.5"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/conallob/mcp-omnifocus/releases/download/v0.0.5/mcp-omnifocus_0.0.5_darwin_x86_64.tar.gz"
    sha256 "9e67d2a71093aed49d6c5159a3a405ab7d694a3d7e0801314fd2efc250c50e65"

    def install
      bin.install "mcp-omnifocus"
      (share/"mcp-omnifocus").install Dir["scripts/*.jxa"]
      (share/"mcp-omnifocus").install "config-example.json"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/conallob/mcp-omnifocus/releases/download/v0.0.5/mcp-omnifocus_0.0.5_darwin_arm64.tar.gz"
    sha256 "be1c14f87a19877e4b2ecdd374d779ccd8cfde804cc166da4eb3a5a5c3e31a4b"

    def install
      bin.install "mcp-omnifocus"
      (share/"mcp-omnifocus").install Dir["scripts/*.jxa"]
      (share/"mcp-omnifocus").install "config-example.json"
    end
  end

  def caveats
    <<~EOS
      The JXA scripts are installed to:
        #{share}/mcp-omnifocus/scripts/

      An example configuration file is available at:
        #{share}/mcp-omnifocus/config-example.json

      Follow the Quick Start Guide for setup instructions:
        https://github.com/conall/mcp-omnifocus/blob/main/QUICKSTART.md
    EOS
  end
end
