# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpGoogleSheets < Formula
  desc "MCP server for Google Sheets API integration"
  homepage "https://github.com/conallob/mcp-google-sheets"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/conallob/mcp-google-sheets/releases/download/v1.0.0/mcp-google-sheets_1.0.0_Darwin_x86_64.tar.gz"
      sha256 "bf3abb2dc376ee741642d8b3de223e8f18a94ddeaae71ebcecfb26d9e73e720c"

      define_method(:install) do
        bin.install "mcp-google-sheets"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/conallob/mcp-google-sheets/releases/download/v1.0.0/mcp-google-sheets_1.0.0_Darwin_arm64.tar.gz"
      sha256 "95e4485bbfb6fb8ee9e7a5a69860fdad27b209ce41a06d14db71f91433aad34e"

      define_method(:install) do
        bin.install "mcp-google-sheets"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/conallob/mcp-google-sheets/releases/download/v1.0.0/mcp-google-sheets_1.0.0_Linux_x86_64.tar.gz"
      sha256 "1c1e5a9db32578d9e072bcfb6cb5e501b2195d1a531c44ee21bbcf1e7fa30031"
      define_method(:install) do
        bin.install "mcp-google-sheets"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/conallob/mcp-google-sheets/releases/download/v1.0.0/mcp-google-sheets_1.0.0_Linux_arm64.tar.gz"
      sha256 "64a5b0a8eebf4ef263d7bc466b2eb9071133f73ffb9bad54005407cf332ac991"
      define_method(:install) do
        bin.install "mcp-google-sheets"
      end
    end
  end

  def caveats
    <<~EOS
      To use mcp-google-sheets, you need to:
      1. Set up Google Sheets API credentials (see SETUP.md)
      2. Set the GOOGLE_APPLICATION_CREDENTIALS environment variable

      For detailed setup instructions, visit:
      https://github.com/conallob/mcp-google-sheets/blob/main/SETUP.md
    EOS
  end

  test do
    system "#{bin}/mcp-google-sheets", "--version"
  end
end
