# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpJetkvm < Formula
  desc "MCP server for JetKVM device control, screenshots, and video capture"
  homepage "https://github.com/conallob/mcp-jetkvm"
  version "0.0.2"
  license "BSD-3-Clause"

  depends_on "ffmpeg"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/conallob/mcp-jetkvm/releases/download/v0.0.2/mcp-jetkvm_darwin_amd64.tar.gz"
      sha256 "ece545838e2c3d7969c9bcaa19e60f69ba9e54bca188ac7368196e224893c514"

      define_method(:install) do
        bin.install "mcp-jetkvm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/conallob/mcp-jetkvm/releases/download/v0.0.2/mcp-jetkvm_darwin_arm64.tar.gz"
      sha256 "97eade8dc197007405c8e799315758457afbd2fdd536099bb860f85a3e697092"

      define_method(:install) do
        bin.install "mcp-jetkvm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/conallob/mcp-jetkvm/releases/download/v0.0.2/mcp-jetkvm_linux_amd64.tar.gz"
      sha256 "c970275232365d5471028ccc30acac29fb273c9025fa43c74ac08926eab0116c"
      define_method(:install) do
        bin.install "mcp-jetkvm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/conallob/mcp-jetkvm/releases/download/v0.0.2/mcp-jetkvm_linux_arm64.tar.gz"
      sha256 "4af5dac24062219f05862cf31ce22646da9369c832efed112b441d5c1551062a"
      define_method(:install) do
        bin.install "mcp-jetkvm"
      end
    end
  end

  test do
    system "#{bin}/mcp-jetkvm", "--help" rescue nil
  end
end
