# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpOmnifocus < Formula
  desc "MCP server for interacting with OmniFocus Pro through its automation API"
  homepage "https://github.com/conall/mcp-omnifocus"
  version "0.0.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/conallob/mcp-omnifocus/releases/download/v0.0.1/mcp-omnifocus_0.0.1_darwin_x86_64.tar.gz"
    sha256 "666ae761593bd8e290b822c206e77996a0e00534459e2a463bb658e251cf2c50"

    def install
      bin.install "mcp-omnifocus"
      (share/"mcp-omnifocus").install Dir["scripts/*.jxa"]
      (share/"mcp-omnifocus").install "config-example.json"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/conallob/mcp-omnifocus/releases/download/v0.0.1/mcp-omnifocus_0.0.1_darwin_arm64.tar.gz"
    sha256 "d3607aef1978c248e38c897469eaa3be28621c2bd1e3a32b84fd94afa716121f"

    def install
      bin.install "mcp-omnifocus"
      (share/"mcp-omnifocus").install Dir["scripts/*.jxa"]
      (share/"mcp-omnifocus").install "config-example.json"
    end
  end

  def caveats
    <<~EOS
      The JXA scripts are installed to:
        #{share}/mcp-omnifocus/scripts/

      An example configuration file is available at:
        #{share}/mcp-omnifocus/config-example.json

      Follow the Quick Start Guide for setup instructions:
        https://github.com/conall/mcp-omnifocus/blob/main/QUICKSTART.md
    EOS
  end
end
