# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpGoogleSheets < Formula
  desc "MCP server for Google Sheets API integration"
  homepage "https://github.com/conallob/mcp-google-sheets"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/conallob/mcp-google-sheets/releases/download/v0.0.1/mcp-google-sheets_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "5374a35b7ddbf9bec3d3b4a0cc027739498dbd82545a621ef86780252d435436"

      def install
        bin.install "mcp-google-sheets"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/conallob/mcp-google-sheets/releases/download/v0.0.1/mcp-google-sheets_0.0.1_Darwin_arm64.tar.gz"
      sha256 "bba52bb55f0b7f8460904df69f6f45a57269fe47c58cb149c49231c479632fe6"

      def install
        bin.install "mcp-google-sheets"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/conallob/mcp-google-sheets/releases/download/v0.0.1/mcp-google-sheets_0.0.1_Linux_x86_64.tar.gz"
      sha256 "d5943d6c1e7edf41cd101b06d4ae68b79f1fb90570f760401367d4b90b01b38b"
      def install
        bin.install "mcp-google-sheets"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/conallob/mcp-google-sheets/releases/download/v0.0.1/mcp-google-sheets_0.0.1_Linux_arm64.tar.gz"
      sha256 "e510bd0bc0adb820c4fd6cf140445d9d65a78377946395dd51d4d50951894687"
      def install
        bin.install "mcp-google-sheets"
      end
    end
  end

  def caveats
    <<~EOS
      To use mcp-google-sheets, you need to:
      1. Set up Google Sheets API credentials (see SETUP.md)
      2. Set the GOOGLE_APPLICATION_CREDENTIALS environment variable

      For detailed setup instructions, visit:
      https://github.com/conallob/mcp-google-sheets/blob/main/SETUP.md
    EOS
  end

  test do
    system "#{bin}/mcp-google-sheets", "--version"
  end
end
