# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpJetkvm < Formula
  desc "MCP server for JetKVM device control, screenshots, and video capture"
  homepage "https://github.com/conallob/mcp-jetkvm"
  version "0.0.1"
  license "BSD-3-Clause"

  depends_on "ffmpeg"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/conallob/mcp-jetkvm/releases/download/v0.0.1/mcp-jetkvm_darwin_amd64.tar.gz"
      sha256 "ec886e4bd929cff4d3aabf68fe13be1b45c8a93448d551fe69d15520e985db4e"

      define_method(:install) do
        bin.install "mcp-jetkvm"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/conallob/mcp-jetkvm/releases/download/v0.0.1/mcp-jetkvm_darwin_arm64.tar.gz"
      sha256 "270145c3328a01d8962d315c2cf0ec9d240664acd4ace3782d5573f4af8b1347"

      define_method(:install) do
        bin.install "mcp-jetkvm"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/conallob/mcp-jetkvm/releases/download/v0.0.1/mcp-jetkvm_linux_amd64.tar.gz"
      sha256 "e0d41389e1e3486d2679e4396e8d1cb2bd5fd2416b99696da17b5b1e975907d0"
      define_method(:install) do
        bin.install "mcp-jetkvm"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/conallob/mcp-jetkvm/releases/download/v0.0.1/mcp-jetkvm_linux_arm64.tar.gz"
      sha256 "2c0dca414ef4d10aa717fd56f4341cd4d09cfe9a47d5f937cac229e6e84eb6c2"
      define_method(:install) do
        bin.install "mcp-jetkvm"
      end
    end
  end

  test do
    system "#{bin}/mcp-jetkvm", "--help" rescue nil
  end
end
