# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpToshl < Formula
  desc "MCP Server for accessing Toshl Finance transaction data"
  homepage "https://github.com/conallob/mcp-toshl"
  version "0.0.1"
  license "BSD-3-Clause"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/conallob/mcp-toshl/releases/download/v0.0.1/mcp-toshl_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "04ce74e9528ccb7ab7bd92f0df60459c678ae9e31f0fcfed84fdccb7ae174350"

      define_method(:install) do
        bin.install "mcp-toshl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/conallob/mcp-toshl/releases/download/v0.0.1/mcp-toshl_0.0.1_Darwin_arm64.tar.gz"
      sha256 "fc55d4529e341cd99ca06bff84806a8dfbf3c8dc9bafdbe9ebe3504cc5582ea1"

      define_method(:install) do
        bin.install "mcp-toshl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/conallob/mcp-toshl/releases/download/v0.0.1/mcp-toshl_0.0.1_Linux_x86_64.tar.gz"
      sha256 "a570b6216d92231900e553be9942998e887a814f21850048eba560d9edc30c3c"
      define_method(:install) do
        bin.install "mcp-toshl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/conallob/mcp-toshl/releases/download/v0.0.1/mcp-toshl_0.0.1_Linux_arm64.tar.gz"
      sha256 "3e224b5a9cfe1ab07a8f0b420ec7f0b092ac3baa68e6eb2dbd167d6011bc4a11"
      define_method(:install) do
        bin.install "mcp-toshl"
      end
    end
  end

  test do
    system "#{bin}/mcp-toshl --version"
  end
end
