# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class O11yAnalysisTools < Formula
  desc "Static analysis and testing tools for PromQL-compatible monitoring systems"
  homepage "https://github.com/conallob/o11y-analysis-tools"
  version "0.0.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/conallob/o11y-analysis-tools/releases/download/v0.0.4/o11y-analysis-tools_0.0.4_Darwin_x86_64.tar.gz"
      sha256 "1429653da01d75dbb66bfa31ad7511290837ff85f764394f48151e553d1cd799"

      def install
        bin.install "promql-fmt"
        bin.install "label-check"
        bin.install "alert-hysteresis"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/conallob/o11y-analysis-tools/releases/download/v0.0.4/o11y-analysis-tools_0.0.4_Darwin_arm64.tar.gz"
      sha256 "24a329245410515cbbb2fe892fbd9756dbe6f8c7901850984d7459b303b65a7c"

      def install
        bin.install "promql-fmt"
        bin.install "label-check"
        bin.install "alert-hysteresis"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/conallob/o11y-analysis-tools/releases/download/v0.0.4/o11y-analysis-tools_0.0.4_Linux_x86_64.tar.gz"
      sha256 "d1b8381181802a3eed855d9750691706821528f364596da9f4949b4c41d433a7"
      def install
        bin.install "promql-fmt"
        bin.install "label-check"
        bin.install "alert-hysteresis"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/conallob/o11y-analysis-tools/releases/download/v0.0.4/o11y-analysis-tools_0.0.4_Linux_arm64.tar.gz"
      sha256 "b03e5a55a4d265c071e9ca696512c11b5d602f5f803108c6b3b0944170c38a09"
      def install
        bin.install "promql-fmt"
        bin.install "label-check"
        bin.install "alert-hysteresis"
      end
    end
  end

  test do
    system "#{bin}/promql-fmt", "--help"
    system "#{bin}/label-check", "--help"
    system "#{bin}/alert-hysteresis", "--help"
  end
end
