# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class O11yAnalysisTools < Formula
  desc "Static analysis and testing tools for PromQL-compatible monitoring systems"
  homepage "https://github.com/conallob/o11y-analysis-tools"
  version "0.0.8"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/conallob/o11y-analysis-tools/releases/download/v0.0.8/o11y-analysis-tools_0.0.8_Darwin_x86_64.tar.gz"
      sha256 "ac2fea26738952e302dd025c7517226505cc4e258fd5f6773e9dd01f1c1da377"

      define_method(:install) do
        bin.install "promql-fmt"
        bin.install "label-check"
        bin.install "alert-hysteresis"
        bin.install "autogen-promql-tests"
        bin.install "e2e-alertmanager-test"
        bin.install "stale-alerts-analyzer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/conallob/o11y-analysis-tools/releases/download/v0.0.8/o11y-analysis-tools_0.0.8_Darwin_arm64.tar.gz"
      sha256 "4242642ce9ee428630a1e5855d86d69749f38b9cce386a9eb1ea368ccb4742b6"

      define_method(:install) do
        bin.install "promql-fmt"
        bin.install "label-check"
        bin.install "alert-hysteresis"
        bin.install "autogen-promql-tests"
        bin.install "e2e-alertmanager-test"
        bin.install "stale-alerts-analyzer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/conallob/o11y-analysis-tools/releases/download/v0.0.8/o11y-analysis-tools_0.0.8_Linux_x86_64.tar.gz"
      sha256 "f7a6f827ad60da661a7d78c5b6a0049c03a89a4dd02a3f531b18f316e16c420d"
      define_method(:install) do
        bin.install "promql-fmt"
        bin.install "label-check"
        bin.install "alert-hysteresis"
        bin.install "autogen-promql-tests"
        bin.install "e2e-alertmanager-test"
        bin.install "stale-alerts-analyzer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/conallob/o11y-analysis-tools/releases/download/v0.0.8/o11y-analysis-tools_0.0.8_Linux_arm64.tar.gz"
      sha256 "27ac085020b1524d122151fad78a39c7d13e39d34da09e7c3dbf0f75a754d129"
      define_method(:install) do
        bin.install "promql-fmt"
        bin.install "label-check"
        bin.install "alert-hysteresis"
        bin.install "autogen-promql-tests"
        bin.install "e2e-alertmanager-test"
        bin.install "stale-alerts-analyzer"
      end
    end
  end

  test do
    system "#{bin}/promql-fmt", "--help"
    system "#{bin}/label-check", "--help"
    system "#{bin}/alert-hysteresis", "--help"
    system "#{bin}/autogen-promql-tests", "--help"
    system "#{bin}/e2e-alertmanager-test", "--help"
    system "#{bin}/stale-alerts-analyzer", "--help"
  end
end
