# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class O11yAnalysisTools < Formula
  desc "Static analysis and testing tools for PromQL-compatible monitoring systems"
  homepage "https://github.com/conallob/o11y-analysis-tools"
  version "0.0.7"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/conallob/o11y-analysis-tools/releases/download/v0.0.7/o11y-analysis-tools_0.0.7_Darwin_x86_64.tar.gz"
      sha256 "d8708d23a5f5c603d25e0b6fbd96bc176668b9df8fd23fb29223ed650227b337"

      def install
        bin.install "promql-fmt"
        bin.install "label-check"
        bin.install "alert-hysteresis"
        bin.install "autogen-promql-tests"
        bin.install "e2e-alertmanager-test"
        bin.install "stale-alerts-analyzer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/conallob/o11y-analysis-tools/releases/download/v0.0.7/o11y-analysis-tools_0.0.7_Darwin_arm64.tar.gz"
      sha256 "84d208967e214282f85c1a012791317cff2a596cfea7034b38431b0f975c670c"

      def install
        bin.install "promql-fmt"
        bin.install "label-check"
        bin.install "alert-hysteresis"
        bin.install "autogen-promql-tests"
        bin.install "e2e-alertmanager-test"
        bin.install "stale-alerts-analyzer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/conallob/o11y-analysis-tools/releases/download/v0.0.7/o11y-analysis-tools_0.0.7_Linux_x86_64.tar.gz"
      sha256 "7fcdfebc14cdcefc4e1cef491f71a7f74aff1d7986c983b9a09355b5e2f073f9"
      def install
        bin.install "promql-fmt"
        bin.install "label-check"
        bin.install "alert-hysteresis"
        bin.install "autogen-promql-tests"
        bin.install "e2e-alertmanager-test"
        bin.install "stale-alerts-analyzer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/conallob/o11y-analysis-tools/releases/download/v0.0.7/o11y-analysis-tools_0.0.7_Linux_arm64.tar.gz"
      sha256 "c69f990593dec132c42b1b97cf27ac262dfa0ba33274268ce671919f68451e69"
      def install
        bin.install "promql-fmt"
        bin.install "label-check"
        bin.install "alert-hysteresis"
        bin.install "autogen-promql-tests"
        bin.install "e2e-alertmanager-test"
        bin.install "stale-alerts-analyzer"
      end
    end
  end

  test do
    system "#{bin}/promql-fmt", "--help"
    system "#{bin}/label-check", "--help"
    system "#{bin}/alert-hysteresis", "--help"
    system "#{bin}/autogen-promql-tests", "--help"
    system "#{bin}/e2e-alertmanager-test", "--help"
    system "#{bin}/stale-alerts-analyzer", "--help"
  end
end
