# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Peridot < Formula
  desc "Cache-aware, multi-source wallpaper rotation daemon"
  homepage "https://github.com/conallob/peridot"
  version "0.0.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/conallob/peridot/releases/download/v0.0.2/peridot_darwin_amd64.tar.gz"
      sha256 "a128d7c75cc87b2b7af3546f8958e45bf60f531eedcae598a04e8d3f1349247b"

      define_method(:install) do
        bin.install "peridotd"
        bin.install "peridot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/conallob/peridot/releases/download/v0.0.2/peridot_darwin_arm64.tar.gz"
      sha256 "c2a3077b927db926cf588f9463cb1d0b1f6ba95ec47b8c73dfd0909573d1c642"

      define_method(:install) do
        bin.install "peridotd"
        bin.install "peridot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/conallob/peridot/releases/download/v0.0.2/peridot_linux_amd64.tar.gz"
      sha256 "83be59d8038d46289c34d957849d7bea2073878d4b87a653d8b4926f125cb739"
      define_method(:install) do
        bin.install "peridotd"
        bin.install "peridot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/conallob/peridot/releases/download/v0.0.2/peridot_linux_arm64.tar.gz"
      sha256 "e9b26f02f6f59a14cb402eba64a20373bb05d867c0c1332d68d7f924cf2b31fe"
      define_method(:install) do
        bin.install "peridotd"
        bin.install "peridot"
      end
    end
  end

  test do
    system "#{bin}/peridot", "--version"
  end
end
